import type { Metadata } from "next";
import { LegalPageLayout } from "../components/legal-page-layout";

export const metadata: Metadata = {
  title: "Terms of Use | PalmVibe",
  description: "Terms governing your use of PalmVibe AI palm reading and compatibility previews.",
};

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Use">
      <p className="text-zinc-200">
        Last updated: May 1, 2026. By accessing or using PalmVibe, you agree to these terms. If
        you do not agree, please do not use the service.
      </p>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">Entertainment Use Only</h2>
        <p>
          PalmVibe is provided for{" "}
          <strong className="font-medium text-zinc-200">entertainment and self-reflection</strong>{" "}
          only. Readings and scores are generated by AI and are not facts about your future,
          health, or relationships.
        </p>
        <p>
          PalmVibe does <strong className="font-medium text-zinc-200">not</strong> guarantee
          prediction accuracy, completeness, or usefulness for any purpose.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">Eligibility</h2>
        <p>
          You must be old enough in your place of residence to enter into a binding agreement and
          to make online purchases where applicable. If you are not, you may not use PalmVibe.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">User Uploads</h2>
        <p>
          You must not upload images you do not own or do not have the right to use, or images of
          other people without permission where required. You are responsible for your uploads and
          for complying with applicable laws.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">AI-Generated Reports</h2>
        <p>
          Reports are AI-generated and may be inaccurate, incomplete, offensive, or unexpected.
          PalmVibe may update or discontinue features at any time. You use outputs at your own
          risk.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">No Professional Advice</h2>
        <p>
          PalmVibe does not provide medical, psychological, legal, financial, or major
          relationship decision advice. Do not rely on PalmVibe for those decisions—seek qualified
          professionals when appropriate.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, PalmVibe and its operators are not liable for
          any indirect, incidental, special, consequential, or punitive damages, or any loss of
          profits, data, goodwill, or other intangible losses arising from your use of the
          service, including reliance on AI output.
        </p>
        <p>
          PalmVibe is provided &quot;as is&quot; without warranties of any kind, express or
          implied, except where prohibited by law. Our aggregate liability for any claim relating
          to the service shall not exceed the amount you paid to PalmVibe for the transaction
          giving rise to the claim (if any), or fifty U.S. dollars (USD), whichever is greater,
          unless a different mandatory minimum applies in your jurisdiction.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">Contact</h2>
        <p>
          Questions about these terms:{" "}
          <a
            href="mailto:support@palmvibe.com"
            className="font-medium text-violet-300 underline decoration-violet-500/40 underline-offset-2 hover:text-violet-200"
          >
            support@palmvibe.com
          </a>
        </p>
      </section>
    </LegalPageLayout>
  );
}
